apiVersion: apps/v1
kind: Deployment
metadata:
  name: antrea-toolbox
  namespace: lfx-mentorship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antrea-toolbox
  template:
    metadata:
      labels:
        app: antrea-toolbox
    spec:
      containers:
      - name: toolbox
        image: antrea/toolbox:1.4
        command: ["/bin/sleep", "3650d"] 
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi